print("Please enter the following information:")
print(' ')
last_name=input('Please enter your last name: ')
first_name=input('Please enter your first name: ')
job_title=input('Please enter your Job Title: ')
id_number=input('Please enter your work ID number: ')
email_address=input('Please enter your email address: ')
phone_number=input('Please enter your Phone number: ')
print(' ')
print('The ID card is:')
print('---------------------------------------------')
print(f"{last_name.upper()}, {first_name.capitalize()}")
print(job_title.capitalize())
print('ID: '+ id_number)
print(' ')
print(email_address.lower())
print(phone_number)
print('---------------------------------------------')