print('Please enter the following:')
print(' ')
adjective=input('Please enter an Adjective: ')
animal=input('Please enter an Animal: ')
first_verb=input('Please enter a Verb: ')
exclamation=input('Please enter an Exclamation: ')
second_verb=input('Please enter another Verb: ')
third_verb=input('Please enter another Verb: ')

print(' ')
print('The other day, I was really in trouble. It all started when I saw a very')
print(adjective + ' ' + animal + ' ' + first_verb + ' down the hallway. \"' + exclamation.capitalize() + '!\" I yelled. But all')
print('I could think to do was to ' + second_verb + ' over and over. Miraculously,')
print('that caused it to stop, but not before it tried to ' + third_verb)
print('right in front of my family.')
print(' ')
print('Thank you for playing!')
